image: node:16

stages:
  - container
  - deploy

build_image:
  image: docker:latest
  stage: container
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --build-arg SPEAKEASY_VER=$CI_COMMIT_REF_NAME --no-cache -t docker-registry.xx.network/elixxir/speakeasy-web:$CI_COMMIT_REF_NAME .
    - docker push docker-registry.xx.network/elixxir/speakeasy-web:$CI_COMMIT_REF_NAME
  only:
    - staging
    - dev
    - backend-dev
    - tags
  tags:
    - dind

deploy_preprod:
  stage: deploy
  script:
    - apt update
    - apt install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh -o StrictHostKeychecking=no maint@142.93.100.204 "sudo service speakeasy restart"
    - echo Redeployed http://stg.speakeasy.tech/
  only:
    - staging

deploy_dev:
  stage: deploy
  script:
    - apt update
    - apt install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh -o StrictHostKeychecking=no maint@167.71.42.39 "sudo service speakeasy restart"
    - echo Redeployed http://dev.speakeasy.tech/
  only:
    - dev

deploy_backdev:
  stage: deploy
  script:
    - apt update
    - apt install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    
    - ssh -o StrictHostKeychecking=no maint@165.227.151.153 "sudo service speakeasy restart"
    - echo Redeployed http://backdev.speakeasy.tech/
  only:
    - backend-dev
