image: ubuntu:20.04

before_script:
  - apt update
  - apt install -y openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - deploy

deploy_preprod:
  stage: deploy
  script:
    - ssh -o StrictHostKeychecking=no maint@142.93.100.204 "sudo service speakeasy restart"
    - echo Redeployed http://stg.speakeasy.tech/
  only:
    - staging

deploy_dev:
  stage: deploy
  script:
    - ssh -o StrictHostKeychecking=no maint@167.71.42.39 "sudo service speakeasy restart"
    - echo Redeployed http://dev.speakeasy.tech/
  only:
    - dev
