image: ubuntu:20.04

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
    - deploy

deploy_preprod:
  stage: deploy
  script:
    - ssh -o StrictHostKeychecking=no maint@142.93.100.204 "service speakeasy restart"
    - echo Redeployed http://main.speakeasy.tech/
  only:
    - main

deploy_dev:
  stage: deploy
  script:
    - ssh -o StrictHostKeychecking=no maint@167.71.42.39 "service speakeasy restart"
    - echo Redeployed http://dev.speakeasy.tech/
  only:
    - dev
